<?php

use App\Facade\ProviderFacade;
use App\Integration\CardInformationProviderInterface;
use PHPUnit\Framework\TestCase;

class CardInformationProviderTest extends TestCase
{
    private CardInformationProviderInterface $cardInformationProvider;

    public function testGetExistingCardInformation()
    {
        $cardInformation = $this->cardInformationProvider->getCardInformation('45717360');
        $this->assertEquals('DK', $cardInformation->getCountryAlfa2Code());
    }

    public function testGetValidNonExistingCardInformation()
    {
        $cardInformation = $this->cardInformationProvider->getCardInformation('444111');
        $this->assertNotNull($cardInformation->getCountryAlfa2Code());
    }

    public function testGetNotValidCardInformation()
    {
        $cardInformation = $this->cardInformationProvider->getCardInformation('44411');
        $this->assertNull($cardInformation->getCountryAlfa2Code());
    }

    protected function setUp(): void
    {
        $this->cardInformationProvider = ProviderFacade::getCardInformationProvider();
        parent::setUp(); // TODO: Change the autogenerated stub
    }
}