<?php

use App\Service\TransactionService;
use PHPUnit\Framework\TestCase;

class TransactionServiceTest extends TestCase
{
    private TransactionService $transactionService;
    private string $fileName = 'tests/test_transactions.txt';

    public function testTransactionsParsing()
    {
        $transactions = [
            ['bin' => '000000', 'amount' => 1000, 'currency' => 'EUR'],
            ['bin' => '000001', 'amount' => 2000, 'currency' => 'USD'],
        ];
        $this->saveTransactions($transactions);
        $parsedTransactions = $this->transactionService->readTransactionsFromFile($this->fileName);
        foreach ($parsedTransactions as $index => $transaction) {
            $original = $transactions[$index];
            $this->assertEquals($original['bin'], $transaction->getBin());
            $this->assertEquals($original['amount'], $transaction->getAmount());
            $this->assertEquals($original['currency'], $transaction->getCurrency());
        }
    }

    public function testParsingMissingFieldsInTransactions()
    {
        $transactions = [
            ['bin_is_missing' => '000000', 'amount' => 1000, 'currency' => 'EUR'],
        ];
        $this->saveTransactions($transactions);
        $this->expectException(\Exception::class);
        $this->transactionService->readTransactionsFromFile($this->fileName);
    }

    public function testWithNotValidJsonFile()
    {
        $this->saveTransactions(['wrong json']);
        $this->expectException(\Exception::class);
        $this->transactionService->readTransactionsFromFile($this->fileName);
    }

    public function setUp(): void
    {
        parent::setUp();
        $this->transactionService = new TransactionService();
    }

    public function tearDown(): void
    {
        if (file_exists($this->fileName)) {
            unlink($this->fileName);
        }
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    private function saveTransactions(array $transactions)
    {
        $file = fopen($this->fileName, 'w');
        foreach ($transactions as $transaction) {
            fwrite($file, json_encode($transaction) . PHP_EOL);
        }
    }
}
