<?php

use App\Service\TransactionService;
use PHPUnit\Framework\TestCase;

class TransactionServiceTest extends TestCase
{
    private string $fileName = 'tests/test_transactions.txt';

    public function testTransactionsParsing()
    {
        $transactions = [
            ['bin' => '000000', 'amount' => 1000, 'currency' => 'EUR'],
        ];
        $file = fopen($this->fileName, 'w');
        foreach ($transactions as $transaction) {
            fwrite($file, json_encode($transaction) . PHP_EOL);
        }
        $transactionService = new TransactionService();
        $parsedTransactions = $transactionService->readTransactionsFromFile($this->fileName);
        foreach ($parsedTransactions as $index => $transaction) {
            $original = $transactions[$index];
            $this->assertEquals($original['bin'], $transaction->getBin());
            $this->assertEquals($original['amount'], $transaction->getAmount());
            $this->assertEquals($original['currency'], $transaction->getCurrency());
        }
    }

    public function tearDown(): void
    {
        if (file_exists($this->fileName)) {
            unlink($this->fileName);
        }
        parent::tearDown(); // TODO: Change the autogenerated stub
    }
}
